name: Go

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: go build -v ./...
    - run: go test -v ./...
    - run: gh auth status
