name: Go

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: go build -v ./...
    - run: go test -v ./...
    - run: echo sheesh > ok.txt
    - run: gh release upload v1 ok.txt --clobber
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
